server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youlexuandb?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.188.129
    port: 6379
mybatis:
  mapper-locations: classpath:com/offcn/mapper/*.xml
  type-aliases-package: com.offcn.pojo
dubbo:
  application:
    name: youlexuan-goods-service-boot
  registry:
    address: zookeeper://192.168.188.129:2181
  protocol:
    port: 20881
pagehelper:
  helper-dialect: mysql